# fly.toml app configuration file generated for appka-pro-honzika on 2025-10-15T15:25:55Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'appka-pro-honzika'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

  
[mounts]
  source = "data"
  destination = "/data"